function top(){
	var str='<div id="theader" class="theader">'
			+'	<div id="theader-left" class="theader-left"> '
			+'		<a id="qdl" class="qdl" style="color: #0E97E6;">亲，请登录</a> '
			+'		<a id="zc" class="zc">免费注册</a><a id="sj" class="sj">手机逛鞋城</a>'
			+'	</div>'
			+'	<div id="theader-right" class="theader-right">'
			+'		<ul class="gwc_r_ul">'
			+'			<li><a href="huiyuan.html">个人中心<img src="img/xialalogo.png"></a></li>'
			+'			<li><a href="whechat.html">消息中心<img class="tr_img" src="img/xialalogo.png"><span id="xiaoxin" class="tr_span">3</span></a></li> '
			+'	</ul> '
			+'	</div> '
			+'</div> '
			+' <div id="tfooter" class="tfooter footer_bg">'
			+'	<div id="tfooter-logo" class="tfooter-logo">'
			+'		<img class="logo_wh" src="img/sclogo.png" />'
			+'	</div>'
			+'	<div id="tfooter-search" class="tfooter-search">'
			+'		<div id="ts-select" class="ts-select">'
			+'			<a href="#" class="active">鞋样搜索</a>'
			+'			<a href="#">鞋底搜索</a>'
			+'		</div>'
			+'		<div id="ts-sousuo" class="ts-sousuo">'
			+'			<input type="text" name="ts-sousuo-txt" id="ts-sousuo-txt" placeholder="编号、名称、类别、属性……">'
			+'			<input type="button" id="ts-sousuo-btn" value="搜 索" name="ts-sousuo-btn">'
			+'		</div>'
			+'		<div id="ts-condition" class="ts-condition">'
			+'			<div id="tsc-close">'
			+'				<a href="#"><img src="img/guanbi.png" /></a>'
			+'			</div>'
			+'			<div class="sx_updown clearfix">'
			+'				<div class="sousuo clearfix">'
			+'					<div class="select-result clearfix">'
			+'						<ul id="select_ul">'
			+'						</ul>'
			+'					</div>'
			+'				</div>'
			+'				<div class="sx_content">'
			+'					<div class="updown_box w290">'
			+'						<h3>按品牌</h3>'
			+'						<ul id="select1">'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">孺子牛</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">晶丽</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">远港</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">老北京布鞋</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">Adidas</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">Nike</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">ANTA</a>'
			+'							</li>'
			+'							<li>'
			+'								<a href="javascript:;">LINING</a>'
			+'							</li>'
			+'							<li data-num="select1">'
			+'								<a href="javascript:;">回古</a>'
			+'							</li>'
			+'						</ul>'
			+'					</div>'
			+'					<div class="updown_box w160">'
			+'						<h3>款式</h3>'
			+'						<ul id="select2">'
			+'							<li date-type="1">'
			+'								<a href="javascript:;">2016</a>'
			+'							</li>'
			+'							<li date-type="2">'
			+'								<a href="javascript:;">2015</a>'
			+'							</li>'
			+'							<li date-type="3">'
			+'								<a href="javascript:;">气垫</a>'
			+'							</li>'
			+'							<li date-type="4">'
			+'								<a href="javascript:;">软性</a>'
			+'							</li>'
			+'							<li date-type="5">'
			+'								<a href="javascript:;">硬性</a>'
			+'							</li>'
			+'							<li date-type="6">'
			+'								<a href="javascript:;">橡胶</a>'
			+'							</li>'
			+'							<li date-type="7">'
			+'								<a href="javascript:;">塑料</a>'
			+'							</li>'
			+'						</ul>'
			+'					</div>'
			+'					<div class="updown_box w160">'
			+'						<h3>按季节</h3>'
			+'						<ul id="select3">'
			+'							<li data-num="select3">'
			+'								<a href="javascript:;">春</a>'
			+'							</li>'
			+'							<li data-num="select3">'
			+'								<a href="javascript:;">夏</a>'
			+'							</li>'
			+'							<li data-num="select3">'
			+'								<a href="javascript:;">秋</a>'
			+'							</li>'
			+'							<li data-num="select3">'
			+'								<a href="javascript:;">冬</a>'
			+'							</li>'
			+'							<li data-num="select3">'
			+'								<a href="javascript:;">通用</a>'
			+'							</li>'
			+'						</ul>'
			+'					</div>'
			+'				</div>'
			+'			</div>'
			+'		</div>'
			+'	</div>'
			+'</div>'
			+'<div id="cc-daohang" class="cc-daohang" name="cc-daohang">'
			+'	<a href="erji.html" class="ej_a1">所有产品分类</a>'
			+'	<ul class="dh_ul dh_ul_qx">'
			+'		<li class="dh_ul_li dh_ul_li_gww" name="dh_ul_li">'
			+'			<a href="pc_index.html" class="dh_ul_li_a ddh">首页</a>'
			+'		</li>'

			+'		<li class="dh_ul_li dh_ul_li_gww" name="dh_ul_li">'
			+'			<a href="#" class="dh_ul_li_a ddh">男装区</a>'
						
			+'		</li>'

			+'		<li class="dh_ul_li dh_ul_li_gww" name="dh_ul_li">'
			+'			<a href="#" class="dh_ul_li_a ddh">女装区</a>'
						
			+'		</li>'
			+'		<li class="dh_ul_li dh_ul_li_gww" style="width: 1%; width: 1% !important;">|</li>'
			+'		<li class="dh_ul_li dh_ul_li_gww" name="dh_ul_li">'
			+'			<a href="#" class="dh_ul_li_a">情侣区</a>'
					
			+'		</li>'
			+'		<li class="dh_ul_li dh_ul_li_gww" name="dh_ul_li">'
			+'			<a href="#" class="dh_ul_li_a">童装区</a>'
						
			+'		</li>'
			+'		<li class="dh_ul_li dh_ul_li_gww" name="dh_ul_li">'
			+'			<a href="#" class="dh_ul_li_a">四季款</a>'		
			+'		</li>'
			+'	</ul>'
			+'	<a href="#" class="ej_a ej_ap">手机版</a>'
			+'</div>'
			+'alert(str);'
			
		}
window.onload=function(){
	top();
}
